name: Download and Upload CSV

on:
  workflow_dispatch:

jobs:
  download-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright and dependencies
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run download script
        run: python main.py  # Change this to your actual .py filename

      - name: Upload downloaded CSV
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-report
          path: artifacts/report.csv
