name: Run Playwright Script

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.54.0-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
