name: Scheduled AR Travels Automation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # Runs every day at 5:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.54.0-jammy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AR CSV Download Script
        run: python main.py
