name: Cron Test

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (UTC time)
  workflow_dispatch: # Allows manual trigger

jobs:
  print-time:
    runs-on: ubuntu-latest
    steps:
      - name: Show UTC time
        run: date -u

      - name: Show India time
        run: TZ='Asia/Kolkata' date

